all:
  children:
    bare_metals:
      hosts:
        node-metal-001:
          ip: 127.0.0.1
    kube_control_plane:
      children:
        bare_metals:
    kube_node:
      children:
        bare_metals:
    etcd:
      children:
        bare_metals:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
